#!/usr/bin/env bash
#Install nginx on your web-01 server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo rm /var/www/html/*
sudo touch /var/www/html/index.html
sudo chmod 666 /var/www/html/index.html
echo "Hello World!" >> /var/www/html/index.html
sudo service nginx restart
