#!/usr/bin/env bash
# Redirection page
sudo apt-get -y update
sudo apt-get -y install nginx
sudo rm /var/www/html/*
sudo touch /var/www/html/index.html
sudo chmod 666 /var/www/html/index.html
echo "Hello World!" >> /var/www/html/index.html
new_string="server_name _;\n\n\tlocation \redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"
sudo sed -i "0,/server_name _;/{s|server_name _;|$new_string|}" /etc/nginx/sites-available/default
sudo service nginx restart
