#!/usr/bin/env bash
# Configuring HAProxy

sudo apt-get update
sudo apt-get install -y haproxy
proxy_line="
frontend first_frontend
    bind :80
    default_backend web_servers
    
backend web_servers
    balance roundrobin
    server web-01 3.91.150.95
    server web-02 50.17.75.16"

echo "$proxy_line" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
